name: drift_network_bridge
description: Middleware Network bridge support for drift
version: 0.0.1

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  collection: ^1.16.0
  drift: ^2.0.0
  postgres:
  meta: ^1.8.0
  json_serializable:
  stream_channel:
  uuid:
  typed_data:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.18.0
  mqtt_client:
  drift_testcases:
    path: ../integration_tests/drift_testcases
  json_annotation:
  build_runner:
  mockito:

dependency_overrides:
  drift:
    path: ../../drift
  postgres:
    git:
      url: https://github.com/isoos/postgresql-dart.git
