name: drift
issue_tracker: https://github.com/simolus3/drift/issues
version: 0.0.1
material_icon_code_point: '0xf41e'

# ??? https://github.com/flutter/devtools/issues/6539
issueTracker: https://github.com/simolus3/drift/issues
materialIconCodePoint: "0xf41e"
